language: php

php:
  - 7.3
  - 7.2
  - 7.1

before_script:
  - composer selfupdate

script:
  - composer install
  - vendor/bin/phpcs -n --report-full --report-checkstyle=target/reports/phpcs.xml --extensions=php --standard=PSR2 --ignore=.metadata src
  - vendor/bin/phpunit --bootstrap bootstrap.php --configuration phpunit.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml
